server:
  port: 8080

spring:
  application:
    name: festival-backend

app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
  jwt:
    secret: "festival-auth-development-secret-key-for-local-testing-32-bytes"
    expiration-millis: 3600000
