import type { BoothReservation } from "@/types/booth/booths.types";

const approvedAt = new Date("2026-05-20T10:00:00+09:00").toISOString();

export const initialBoothReservations: BoothReservation[] = [
  {
    id: "booth-reservation-1",
    applicantName: "홍길동",
    boothName: "타코야끼 부스",
    location: "학생회관 앞 A-03",
    status: "APPROVED",
    approvedAt,
    qrCode: null,
    qrFailureReason: null,
    compensationLogs: [],
  },
  {
    id: "booth-reservation-2",
    applicantName: "김민지",
    boothName: "포토카드 교환 부스",
    location: "중앙광장 B-11",
    status: "RESERVED",
    approvedAt,
    qrCode: "QR-BOOTH-RESERVATION-2",
    qrFailureReason: null,
    compensationLogs: [],
  },
  {
    id: "booth-reservation-3",
    applicantName: "이서준",
    boothName: "동아리 굿즈 부스",
    location: "홍문관 뒤 C-07",
    status: "PENDING_APPROVAL",
    approvedAt: null,
    qrCode: null,
    qrFailureReason: null,
    compensationLogs: [],
  },
  {
    id: "booth-reservation-4",
    applicantName: "박하린",
    boothName: "청춘 주점",
    location: "운동장 D-04",
    status: "APPROVED",
    approvedAt,
    qrCode: null,
    qrFailureReason: null,
    compensationLogs: [],
  },
  {
    id: "booth-reservation-5",
    applicantName: "최도윤",
    boothName: "페이스 페인팅 부스",
    location: "중앙광장 E-02",
    status: "CHECKED_IN",
    approvedAt,
    qrCode: "QR-BOOTH-RESERVATION-5",
    qrFailureReason: null,
    compensationLogs: [],
  },
  {
    id: "booth-reservation-6",
    applicantName: "정예린",
    boothName: "업사이클링 체험 부스",
    location: "홍문관 앞 C-12",
    status: "PENDING_APPROVAL",
    approvedAt: null,
    qrCode: null,
    qrFailureReason: null,
    compensationLogs: [],
  },
];
